### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by brylie** [clydeio/clydeio#21]
Hi,
We have a similar project called [Apinf](https://github.com/apinf), which is built around [API Umbrella](http://apiumbrella.io). We are primarily focusing on JavaScript development, using Meteor.js and Node. Would you be interested in collaborating?

**Comment by acanimal** [comment]
Sounds interesting. Please send me an email with more details.

On the other hand, from what I saw in API Umbrella project is the same as other projects, they make one thing (really well) using some tech and in a way. The goal of clydeio is to make a more flexible and modular api gateway.

Waiting your news :)

**Comment by brylie** [comment]
I have contacted you via email.

Based on a quick read of the wiki, I notice ClydeIO is [using Connect middleware for filters](https://github.com/clydeio/clydeio/wiki/Concetps#filter). It is worth mentioning that API Umbrella Gatekeeper project uses Connect as well:
- [package.json](https://github.com/NREL/api-umbrella-gatekeeper/blob/6c1704b51733affb8971bba4d509f27431754008/package.json#L22)
- [API Umbrella Gatekeeper middleware](https://github.com/NREL/api-umbrella-gatekeeper/tree/master/lib/gatekeeper)

**Comment by acanimal** [comment]
Nice, I'll take a look.

What I see is the umbrella middleware are closely related to some backend (redir, mongo).
My goal with clyde is to filters (middlewares) configurations independent on the backend used to store the configuration. I'm working right know on the configuration module that will be probably integrated with the core of clyde.

**Comment by brylie** [comment]
@acanimal I also notice that ClydeIO seems to base its filter model around the request/response cycle. How will the module system be designed to support real-time data streams, such as websockets?

**Comment by acanimal** [comment]
I didn't think on that, for the moment it is oriented for request/response
only. The good is it internally used http-proxy module that supports
websockets.

On Mon, Oct 5, 2015 at 9:29 AM, Brylie Christopher Oxley <
notifications@github.com> wrote:

> @acanimal https://github.com/acanimal I also notice that ClydeIO seems
> to base its filter model around the request/response cycle. How will the
> module system be designed to support real-time data streams, such as
> websockets?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clydeio/clydeio/issues/21#issuecomment-145449357.

## 

|----------------------------------------------------------------
| The book of OpenLayers 3 - http://kcy.me/x29y
| OpenLayers Cookbook: _http://kcy.me/ar2b http://kcy.me/ar2b_
| Blog: http://www.acuriousanimal.com/blog
| Twitter: @acanimal http://twitter.com/#%21/acanimal
|----------------------------------------------------------------
|   _      __
|  /_)    (_ ` _   _  _)_ o  _   _   _
| / /  o .__) (_( ) ) (_  ( (_( (_( (_)
|                                 _)
|----------------------------------------------------------------
