### ISSUE TITLE
Butler renamed Barkley?

### ISSUE THREAD

**Issue by brylie** [clydeio/clydeio#24]
In keeping with the animal spirit and noticing your comment about your current efforts writing Butler, what are your thoughts about renaming that component to Barkley as a tribute to the [Modern Family butler dog](http://modernfamily.wikia.com/wiki/Barkley)?

**Comment by acanimal** [comment]
hahahaha sounds good. From now the code responsible of configuration is known as Barkley :+1:

**Comment by brylie** [comment]
lol cool :dog:
